apiVersion: v1
kind: pod
metadata: 
  name: lables
  namespace: roboshop
  lables:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx      