apiVersion: v1
kind: pod
metadata: 
  name: annotations
  lables:
    project: roboshop
    component: frontend
    environment: dev
  annotations:
    imageregistry: "http://hub.docker.com/"
    jenkinsURL: "http:jenkins.joindevops.com/build/job/roboshop"
spec:
  container:
  - name: nginx
    image: nginx    